import { NextResponse } from "next/server"
import { prisma } from "@/lib/db"
import bcrypt from "bcryptjs"

export async function GET() {
  try {
    const count = await prisma.product.count()
    
    if (count === 0) {
      // Create admin user
      const hashedPassword = await bcrypt.hash("admin123", 12)
      await prisma.user.upsert({
        where: { email: "admin@robowala.com" },
        update: {},
        create: {
          email: "admin@robowala.com",
          name: "Admin User",
          password: hashedPassword,
          role: "ADMIN",
        },
      })

      const products = [
        {
          name: "ESP32-WROOM-32 DevKit",
          slug: "esp32-wroom-32-devkit",
          price: 499,
          originalPrice: 699,
          rating: 4.8,
          reviews: 678,
          image: "/esp32-development-board-wifi-bluetooth-microcontro.jpg",
          category: "Microcontrollers",
          categorySlug: "microcontrollers",
          subcategory: "ESP32 Boards",
          subcategorySlug: "esp32",
          brand: "Espressif",
          badge: "Bestseller",
          inStock: true,
          description: "Powerful WiFi & Bluetooth enabled microcontroller for IoT projects.",
          specifications: JSON.stringify({
            CPU: "Dual-core Xtensa @ 240MHz",
            Flash: "4MB",
            RAM: "520KB SRAM",
            WiFi: "802.11 b/g/n",
            Bluetooth: "BLE 4.2",
            GPIO: "34 pins",
          }),
        },
        {
          name: "Arduino UNO R4 WiFi",
          slug: "arduino-uno-r4-wifi",
          price: 2499,
          originalPrice: 2999,
          rating: 4.9,
          reviews: 312,
          image: "/arduino-uno-r4-wifi-development-board-blue.jpg",
          category: "Arduino",
          categorySlug: "arduino",
          subcategory: "Classic Family",
          subcategorySlug: "arduino-classic",
          brand: "Arduino",
          badge: "New",
          inStock: true,
          description: "Latest Arduino UNO with built-in WiFi, enhanced processing power, and LED matrix.",
          specifications: JSON.stringify({
            CPU: "Renesas RA4M1 (Cortex-M4) @ 48MHz",
            Flash: "256KB",
            RAM: "32KB",
            WiFi: "ESP32-S3",
            "Operating Voltage": "5V",
            "Digital I/O": "14 pins",
            "Analog Input": "6 pins",
          }),
        },
        {
          name: "Raspberry Pi 5 8GB",
          slug: "raspberry-pi-5-8gb",
          price: 7499,
          originalPrice: 8499,
          rating: 4.9,
          reviews: 156,
          image: "/raspberry-pi-5-single-board-computer.jpg",
          category: "Raspberry Pi",
          categorySlug: "raspberry-pi",
          subcategory: "Raspberry Pi 5",
          subcategorySlug: "raspberry-pi-5",
          brand: "Raspberry Pi Foundation",
          badge: "New",
          inStock: true,
          description: "The most powerful Raspberry Pi yet with 8GB RAM, quad-core Cortex-A76 processor, and enhanced connectivity.",
          specifications: JSON.stringify({
            CPU: "Quad-core Cortex-A76 @ 2.4GHz",
            RAM: "8GB LPDDR4X",
            Storage: "microSD card slot",
            USB: "2x USB 3.0, 2x USB 2.0",
            Display: "2x micro HDMI (4K 60fps)",
            GPIO: "40-pin header",
            Connectivity: "Gigabit Ethernet, WiFi 6, Bluetooth 5.2",
          }),
        },
        {
          name: "37-in-1 Sensor Module Kit",
          slug: "37-in-1-sensor-kit",
          price: 1299,
          originalPrice: 1799,
          rating: 4.8,
          reviews: 445,
          image: "/arduino-sensor-kit-37-pieces-various-sensors-modul.jpg",
          category: "Sensors",
          categorySlug: "sensors",
          subcategory: "Sensor Kits",
          subcategorySlug: "sensor-kits",
          brand: null,
          badge: "Kit",
          inStock: true,
          description: "Complete sensor kit with 37 different modules for Arduino and Raspberry Pi.",
          specifications: JSON.stringify({
            "Total Sensors": "37",
            Compatible: "Arduino, Raspberry Pi, ESP32",
            Includes: "Temperature, Humidity, Light, Sound, Motion, Gas, etc.",
            Case: "Plastic storage box included",
          }),
        },
        {
          name: "MG996R High Torque Servo Motor",
          slug: "mg996r-servo",
          price: 349,
          originalPrice: 449,
          rating: 4.6,
          reviews: 523,
          image: "/mg996r-servo-motor-robotics-blue.jpg",
          category: "Motors & Drivers",
          categorySlug: "motors",
          subcategory: "Servo Motors",
          subcategorySlug: "servo-motors",
          brand: "TowerPro",
          badge: "Popular",
          inStock: true,
          description: "High-torque metal gear servo motor for robotics and RC applications.",
          specifications: JSON.stringify({
            Torque: "13kg/cm @ 6V",
            Speed: "0.13s/60° @ 6V",
            "Operating Voltage": "4.8V - 7.2V",
            Weight: "55g",
            Gear: "Metal",
          }),
        },
        {
          name: '0.96" OLED Display I2C 128x64',
          slug: "oled-096-i2c",
          price: 199,
          originalPrice: 299,
          rating: 4.8,
          reviews: 789,
          image: "/oled-display-0-96-inch-i2c-blue-text.jpg",
          category: "Displays",
          categorySlug: "displays",
          subcategory: "OLED Displays",
          subcategorySlug: "oled-displays",
          brand: null,
          badge: "Bestseller",
          inStock: true,
          description: "Compact OLED display module with I2C interface, blue color.",
          specifications: JSON.stringify({
            Size: '0.96"',
            Resolution: "128x64 pixels",
            Interface: "I2C",
            Color: "Blue",
            "Operating Voltage": "3.3V - 5V",
          }),
        },
        {
          name: "NRF24L01+ 2.4GHz Wireless Module",
          slug: "nrf24l01-plus",
          price: 149,
          originalPrice: 199,
          rating: 4.5,
          reviews: 456,
          image: "/nrf24l01-wireless-transceiver-module-green-pcb.jpg",
          category: "Wireless & IoT",
          categorySlug: "wireless",
          subcategory: "RF Modules",
          subcategorySlug: "rf-modules",
          brand: "Nordic",
          badge: "Value",
          inStock: true,
          description: "2.4GHz wireless transceiver module for Arduino and Raspberry Pi.",
          specifications: JSON.stringify({
            Frequency: "2.4GHz ISM band",
            "Data Rate": "250Kbps to 2Mbps",
            Range: "100m (open space)",
            "Operating Voltage": "1.9V - 3.6V",
            Interface: "SPI",
          }),
        },
        {
          name: "4WD Robot Car Chassis Kit",
          slug: "4wd-robot-car-kit",
          price: 1899,
          originalPrice: 2499,
          rating: 4.7,
          reviews: 234,
          image: "/4wd-robot-car-chassis-kit-arduino-compatible.jpg",
          category: "Learning Kits",
          categorySlug: "kits",
          subcategory: "Robotics Kits",
          subcategorySlug: "robotics-kits",
          brand: null,
          badge: "Kit",
          inStock: true,
          description: "Complete 4WD robot car chassis kit with motors and wheels.",
          specifications: JSON.stringify({
            Motors: "4x TT DC Motors",
            Wheels: "4x 65mm diameter",
            Material: "Acrylic",
            "Battery Holder": "4x AA (not included)",
            Dimensions: "200mm x 150mm",
          }),
        },
        {
          name: "DHT22 Temperature & Humidity Sensor",
          slug: "dht22-sensor",
          price: 249,
          originalPrice: 349,
          rating: 4.6,
          reviews: 567,
          image: "/dht22-temperature-humidity-sensor-white.jpg",
          category: "Sensors",
          categorySlug: "sensors",
          subcategory: "Temperature Sensors",
          subcategorySlug: "temperature-sensors",
          brand: "Aosong",
          badge: "Bestseller",
          inStock: true,
          description: "High precision digital temperature and humidity sensor.",
          specifications: JSON.stringify({
            "Temperature Range": "-40°C to 80°C",
            "Temperature Accuracy": "±0.5°C",
            "Humidity Range": "0-100% RH",
            "Humidity Accuracy": "±2% RH",
            Interface: "Single-wire digital",
          }),
        },
        {
          name: "L298N Dual H-Bridge Motor Driver",
          slug: "l298n-motor-driver",
          price: 179,
          originalPrice: 249,
          rating: 4.5,
          reviews: 678,
          image: "/l298n-motor-driver-module-red-pcb.jpg",
          category: "Motors & Drivers",
          categorySlug: "motors",
          subcategory: "Motor Drivers",
          subcategorySlug: "motor-drivers",
          brand: "STMicroelectronics",
          badge: "Bestseller",
          inStock: true,
          description: "Dual H-Bridge motor driver module for controlling DC motors and stepper motors.",
          specifications: JSON.stringify({
            Channels: "2",
            "Max Current": "2A per channel",
            "Peak Current": "3A per channel",
            "Input Voltage": "5V - 35V",
            "Logic Voltage": "5V",
          }),
        },
        {
          name: "HC-SR04 Ultrasonic Distance Sensor",
          slug: "hc-sr04-ultrasonic",
          price: 79,
          originalPrice: 129,
          rating: 4.7,
          reviews: 892,
          image: "/hc-sr04-ultrasonic-sensor-module-blue.jpg",
          category: "Sensors",
          categorySlug: "sensors",
          subcategory: "Proximity Sensors",
          subcategorySlug: "proximity-sensors",
          brand: null,
          badge: "Value",
          inStock: true,
          description: "Ultrasonic distance measuring sensor module, 2cm to 400cm range.",
          specifications: JSON.stringify({
            Range: "2cm - 400cm",
            Accuracy: "3mm",
            "Measuring Angle": "15°",
            "Trigger Input": "10μs TTL pulse",
            "Operating Voltage": "5V DC",
          }),
        },
        {
          name: "NodeMCU ESP8266",
          slug: "nodemcu-esp8266",
          price: 299,
          originalPrice: 399,
          rating: 4.7,
          reviews: 892,
          image: "/nodemcu-esp8266-development-board-blue.jpg",
          category: "Microcontrollers",
          categorySlug: "microcontrollers",
          subcategory: "ESP8266 Boards",
          subcategorySlug: "esp8266",
          brand: "Espressif",
          badge: "Value",
          inStock: true,
          description: "WiFi enabled development board based on ESP8266, perfect for beginners.",
          specifications: JSON.stringify({
            CPU: "Tensilica L106 @ 80MHz",
            Flash: "4MB",
            RAM: "128KB",
            WiFi: "802.11 b/g/n",
            GPIO: "17 pins",
          }),
        }
      ]

      for (const product of products) {
        await prisma.product.create({ data: product })
      }

      return NextResponse.json({ 
        message: `Seeded ${products.length} products`,
        count: products.length 
      })
    }

    return NextResponse.json({ 
      message: "Database already has products",
      count 
    })
  } catch (error) {
    console.error("Database error:", error)
    return NextResponse.json(
      { error: "Database error", details: error.message },
      { status: 500 }
    )
  }
}